services:
  - type: web
    name: documentation-tool-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: MAX_IMAGES
        value: "60"

  - type: web
    name: documentation-tool-frontend
    runtime: node
    buildCommand: |
      cd frontend && \
      rm -rf node_modules package-lock.json && \
      npm install && \
      npm run build
    startCommand: cd frontend && npx next start -p $PORT
    # Alternative start command if the above doesn't work:
    # startCommand: cd frontend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://documentation-tool-backend.onrender.com
      - key: PORT
        value: "3000"
      - key: NODE_VERSION
        value: "18.17.0"
